"""
Django settings for cms_django project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # para cargar variables de entorno desde .env

# Cargar variables de entorno desde archivo .env
load_dotenv()

# Ruta base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================
# CONFIGURACIÓN DE SEGURIDAD
# ============================

# Clave secreta (leer de .env, usar clave por defecto si no existe)
SECRET_KEY = os.getenv('SECRET_KEY', 'clave_por_defecto_muy_insegura')

# Debug activo solo en desarrollo
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Hosts permitidos
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# ============================
# APLICACIONES INSTALADAS
# ============================

INSTALLED_APPS = [
    # Apps Django por defecto
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps propias (modulares)
    'apps.core',  # app principal CMS
    # más adelante agregar: 'apps.blog', 'apps.shop', etc.
]

# ============================
# MIDDLEWARE
# ============================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',       # seguridad general
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',           # protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # clickjacking
]

# ============================
# URLS PRINCIPALES
# ============================

ROOT_URLCONF = 'cms_django.urls'

# ============================
# PLANTILLAS
# ============================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # carpeta global de templates
        'APP_DIRS': True,  # buscar templates en apps también
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # necesario para {{ request }}
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ============================
# WSGI
# ============================

WSGI_APPLICATION = 'cms_django.wsgi.application'

# ============================
# BASE DE DATOS
# ============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # base simple para desarrollo
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================
# VALIDACIÓN DE CONTRASEÑAS
# ============================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},  # mínimo 8 caracteres
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================
# INTERNACIONALIZACIÓN
# ============================

LANGUAGE_CODE = 'es-es'  # español

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True

# ============================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ============================

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # carpeta global de estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles'    # para deploy

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'           # archivos subidos por usuarios

# ============================
# DEFAULT AUTO FIELD
# ============================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
